version: "3"
services:
  mongodb:
    image: mongo:3.2
    volumes:
      - /Users/xywu/Documents/study/data/db:/data/db #数据文件挂载
    ports:
      - 27017:27017
    networks:
      - network

  lab1:
    build: ./
    environment:
      MONGO_URI: mongodb://mongodb:27017/lab
      SERVER_PORT: 9999
    ports:
      - '7777:9999'
    links:
      - mongodb
    networks:
      - network

networks:
  network: {}
